
uplaodBase: "./upload/"
#uploadAddr: "http://101.43.157.116"
uploadAddr: "http://192.168.0.106:8080"

feedVideoCnt: 30

logger: 
  path: "/log"


mysql:
    username: "test"
    password: "674092"
    addr: "101.43.157.116"
    port: "3306"
    database: "tiktok"
    base: "?charset=utf8mb4&parseTime=True&loc=Local"

redis:
    addr: "101.43.157.116:6379"
    password: "579021"
    poolSize: 1000
    minIdleConn: 100
    RedisExpireTime: 120 # 单位h
    KeyVideoList: "zset:video"
    defaultErrorIdentity: -1
    KeyUserHashPrefix: "userinfo:"
    KeyPublishListPrefix: "list:publish:"
    KeyVideoInfoHashPrefix: "videoinfo:"
    KeyCommentInfoHashPrefix: "commentinfo:"
    KeyFavoriteUserSortSetPrefix: "favorite:"
    KeyCommentListPrefix: "list:comment:"
    KeyFollowListPrefix: "list:follow:"
    KeyFollowerSortSetPrefix: "follower:"



md5:
    salt: "tiktokGi0I0R1tC#%"

snowflake:
    machineID: "2345576453432980"

jwt:
    key: "h2wnknlsd"
    expire: 120

currentLimit:
    tokenBucket:
        rate:   1000
        capacity: 5000


rocketmq:
    addr:  "101.43.157.116:9876"
    # 服务的消息队列信息
    serverProducer: "ServerProducer"
    serverTopic:  "ServerTopic"
    retrySize:   2
    followGroupName: "FollowGroup"
    serverFollowTag: "ServerFollow"


    # 重试机制的消息队列信息
    RetryTopic: "RetryTopic"
    RetryGroupName: "RetryGroup"
    RetryQueueRetrySize: 5
    RetryTags: "DeleteFollowRedis"
    DeleteFollowRedisTag: "DeleteFollowRedis"
    


cos:
    addr: "https://tiktok-1310814941.cos.ap-guangzhou.myqcloud.com"
    # SecretId: "AKID2vc5LM9h03sZ0Nn3cO6rcATXNzNXSDjx"
    # SecretKey: "NZcS5WgaFivrVuNbYjzANfrra4KXZNG1"
    SecretId: "AKIDBEaorhLlwrWynzxkKjwunX9Xp02CAwZ3"
    SecretKey: "O62oMhw9C2e7OTKepmV6UgjlmeMtOjtr"


CircuitBreaker:
    roundInterval:  15 # 熔断周期，单位s
    recoverInterval: 5 # 冷却周期，单位s
