
uplaodBase: "./upload/"

logger: 
  path: "/log"


mysql:
    username: "test"
    password: "674092"
    addr: "101.43.157.116"
    port: "3306"
    database: "tiktok"
    base: "?charset=utf8mb4&parseTime=True&loc=Local"

redis:
    addr: "101.43.157.116:6379"
    password: "579021"
    DB: 0
    poolSize: 1000
    minIdleConn: 100
    defaultErrorIdentity: -1
    KeyUserHashPrefix: "userinfo:"
    

md5:
    salt: "tiktokGi0I0R1tC#%"

snowflake:
    machineID: "2345576453432980"

jwt:
    key: "h2wnknlsd"
    expire: 120

currentLimit:
    tokenBucket:
        rate:   1000
        capacity: 5000


rocketmq:
    addr:  "101.43.157.116:9876"
    serverProducer: "ServerProducer"
    serverTopic:  "ServerTopic"
    serverGroupName:  "ServerGroup"
    serverTags: "test||login"
    redisProducer: "RedisProducer"
    redisTopic:  "RedisTopic"
    redisGroupName:  "RedisGroup"
    redisTags: "test||login"
    retrySize:   2


cos:
    addr: "https://tiktok-1310814941.cos.ap-guangzhou.myqcloud.com"
    SecretId: "AKID2vc5LM9h03sZ0Nn3cO6rcATXNzNXSDjx"
    SecretKey: "NZcS5WgaFivrVuNbYjzANfrra4KXZNG1"
    
        