definitions:
  controller.FirendListRespStruct:
    properties:
      status_code:
        type: integer
      status_msg:
        type: string
      user_list:
        items:
          $ref: '#/definitions/service.User'
        type: array
    type: object
  controller.FollowListRespStruct:
    properties:
      status_code:
        type: integer
      status_msg:
        type: string
      user_list:
        items:
          $ref: '#/definitions/service.User'
        type: array
    type: object
  controller.FollowRespStruct:
    properties:
      status_code:
        type: integer
      status_msg:
        type: string
    type: object
  controller.FollowerListRespStruct:
    properties:
      status_code:
        type: integer
      status_msg:
        type: string
      user_list:
        items:
          $ref: '#/definitions/service.User'
        type: array
    type: object
  controller.GetPublishListResponse:
    properties:
      status_code:
        type: integer
      status_msg:
        type: string
      video_list:
        items:
          $ref: '#/definitions/service.Video'
        type: array
    type: object
  controller.UploadRespStruct:
    properties:
      status_code:
        type: integer
      status_msg:
        type: string
    type: object
  service.Author:
    properties:
      follow_count:
        description: default
        type: integer
      follower_count:
        description: default
        type: integer
      id:
        type: integer
      is_follow:
        description: defalut
        type: boolean
      name:
        type: string
    type: object
  service.User:
    properties:
      follow_count:
        type: integer
      follower_count:
        type: integer
      id:
        type: integer
      is_follow:
        type: boolean
      name:
        type: string
    type: object
  service.Video:
    properties:
      author:
        $ref: '#/definitions/service.Author'
      comment_count:
        type: integer
      cover_url:
        type: string
      favorite_count:
        type: integer
      id:
        type: integer
      is_favorite:
        type: boolean
      play_url:
        type: string
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /feed:
    get:
      parameters:
      - description: latest_time
        in: query
        name: latest_time
        type: string
      - description: token
        in: query
        name: token
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 视频流
      tags:
      - 基础接口
  /hello:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 首页
      tags:
      - 公共接口
  /publish/action/:
    post:
      parameters:
      - description: token
        in: formData
        name: token
        required: true
        type: string
      - description: 文件
        in: formData
        name: data
        required: true
        type: file
      - description: 标题
        in: formData
        name: title
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.UploadRespStruct'
      summary: 视频投稿
      tags:
      - 基础接口
  /publish/list/:
    get:
      parameters:
      - description: 登录用户的token
        in: query
        name: token
        required: true
        type: string
      - description: 查找目标用户的id
        in: query
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: status_msg为成功
          schema:
            $ref: '#/definitions/controller.GetPublishListResponse'
      summary: 视频发布列表接口
  /relation/action/:
    post:
      parameters:
      - description: token
        in: query
        name: token
        required: true
        type: string
      - description: 用户id
        in: query
        name: to_user_id
        required: true
        type: string
      - description: 关注操作
        in: query
        name: action_type
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.FollowRespStruct'
      summary: 关注操作
      tags:
      - 社交接口
  /relation/follow/list/:
    get:
      parameters:
      - description: token
        in: query
        name: token
        required: true
        type: string
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.FollowListRespStruct'
      summary: 关注列表
      tags:
      - 社交接口
  /relation/follower/list/:
    get:
      parameters:
      - description: token
        in: query
        name: token
        required: true
        type: string
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.FollowerListRespStruct'
      summary: 粉丝列表
      tags:
      - 社交接口
  /relation/friend/list/:
    get:
      parameters:
      - description: token
        in: query
        name: token
        required: true
        type: string
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.FirendListRespStruct'
      summary: 好友列表
      tags:
      - 社交接口
swagger: "2.0"
