info:
  contact: {}
paths:
  /hello:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 首页
      tags:
      - 公共接口
swagger: "2.0"
