definitions:
  controller.RelationRespStruct:
    properties:
      status_code:
        type: integer
      status_msg:
        type: string
    type: object
  controller.UploadRespStruct:
    properties:
      status_code:
        type: integer
      status_msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /hello:
    get:
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 首页
      tags:
      - 公共接口
  /publish/action/:
    post:
      parameters:
      - description: token
        in: formData
        name: token
        required: true
        type: string
      - description: 文件
        in: formData
        name: data
        required: true
        type: file
      - description: 标题
        in: formData
        name: title
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.UploadRespStruct'
      summary: 视频投稿
      tags:
      - 基础接口
  /relation/action/:
    post:
      parameters:
      - description: token
        in: query
        name: token
        required: true
        type: string
      - description: 用户id
        in: query
        name: to_user_id
        required: true
        type: string
      - description: 关注操作
        in: query
        name: action_type
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.RelationRespStruct'
      summary: 关注操作
      tags:
      - 社交接口
swagger: "2.0"
